cd ../src

../../parallel -j10 --resume-failed --results ../Output/ksync_upset1 --joblog ../joblog/ksync_upset1 CUDA_VISIBLE_DEVICES=0 python ./ksync_train.py --optimizer SGD   --hidden 8 --spectral_step_num 5 --outlier_style {1} --eta {2} --p {3} --N 360 --upset_coeff {4} --cycle_coeff {5} --sync_baseline row_norm_spectral --dataset {6} --k {7} --lr 0.005 --all_methods GNNSync --reg_coeff 0 ::: gamma multi_normal1 multi_normal0 block_normal6 ::: 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 ::: 0.05 0.1 0.15 ::: 1 ::: 1 0 ::: BAO RGGO ERO ::: 4 3 2

../../parallel -j10 --resume-failed --results ../Output/ksync_separate_H --joblog ../joblog/ksync_separate_H CUDA_VISIBLE_DEVICES=0 python ./ksync_train.py --optimizer SGD   --hidden 8 --spectral_step_num 5 --separate_graphs --outlier_style {1} --eta {2} --p {3} --N 360 --upset_coeff {4} --cycle_coeff {5} --sync_baseline row_norm_spectral --dataset {6} --k {7} --lr 0.005 --all_methods GNNSync --reg_coeff 0 ::: gamma multi_normal1 multi_normal0 block_normal6 ::: 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 ::: 0.05 0.1 0.15 ::: 0 ::: 1 ::: BAO RGGO ERO ::: 4 3 2

../../parallel -j10 --resume-failed --results ../Output/ksync_cycle1 --joblog ../joblog/ksync_cycle1 CUDA_VISIBLE_DEVICES=0 python ./ksync_train.py --optimizer SGD   --hidden 8 --spectral_step_num 5 --outlier_style {1} --eta {2} --p {3} --N 360 --upset_coeff {4} --cycle_coeff {5} --sync_baseline row_norm_spectral --dataset {6} --k {7} --lr 0.005 --all_methods GNNSync --reg_coeff 0 ::: gamma multi_normal1 multi_normal0 block_normal6 ::: 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 ::: 0.05 0.1 0.15 ::: 0 0.1 0.3 0.5 0.7 0.9 ::: 1 ::: BAO RGGO ERO ::: 4 3 2

../../parallel -j10 --resume-failed --results ../Output/ksync_no_pgs --joblog ../joblog/ksync_no_pgs CUDA_VISIBLE_DEVICES=0 python ./ksync_train.py --optimizer SGD   --hidden 8 --spectral_step_num 0 --outlier_style {1} --eta {2} --p {3} --N 360 --upset_coeff {4} --cycle_coeff {5} --sync_baseline row_norm_spectral --dataset {6} --k {7} --lr 0.005 --all_methods GNNSync --reg_coeff 0 ::: gamma multi_normal1 multi_normal0 block_normal6 ::: 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 ::: 0.05 0.1 0.15 ::: 0 ::: 1 ::: BAO RGGO ERO ::: 4 3 2

../../parallel -j10 --resume-failed --results ../Output/ksync_two_steps --joblog ../joblog/ksync_two_steps CUDA_VISIBLE_DEVICES=0 python ./two_steps_ksync_train.py --optimizer SGD   --hidden 8 --spectral_step_num 5 --outlier_style {1} --eta {2} --p {3} --N 360 --upset_coeff {4} --cycle_coeff {5} --sync_baseline row_norm_spectral --dataset {6} --k {7} --lr 0.005 --all_methods GNNSync --reg_coeff 0 ::: gamma multi_normal1 multi_normal0 block_normal6 ::: 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 ::: 0.05 0.1 0.15 ::: 0 ::: 1 ::: BAO RGGO ERO ::: 4 3 2

../../parallel -j10 --resume-failed --results ../Output/ksync_trainable_alpha --joblog ../joblog/ksync_trainable_alpha CUDA_VISIBLE_DEVICES=0 python ./ksync_train.py --optimizer SGD   --hidden 8 --spectral_step_num 5 --trainable_alpha --outlier_style {1} --eta {2} --p {3} --N 360 --upset_coeff {4} --cycle_coeff {5} --sync_baseline row_norm_spectral --dataset {6} --k {7} --lr 0.005 --all_methods GNNSync --reg_coeff 0 ::: gamma multi_normal1 multi_normal0 block_normal6 ::: 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 ::: 0.05 0.1 0.15 ::: 0 ::: 1 ::: BAO RGGO ERO ::: 4 3 2

../../parallel -j10 --resume-failed --results ../Output/ksync_spectral --joblog ../joblog/ksync_spectral CUDA_VISIBLE_DEVICES=0 python ./ksync_train.py --optimizer SGD   --hidden 8 --spectral_step_num 5 --outlier_style {1} --eta {2} --p {3} --N 360 --upset_coeff {4} --cycle_coeff {5} --sync_baseline spectral --dataset {6} --k {7} --lr 0.005 --all_methods GNNSync --reg_coeff 0 ::: gamma multi_normal1 multi_normal0 block_normal6 ::: 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 ::: 0.05 0.1 0.15 ::: 0 ::: 1 ::: BAO RGGO ERO ::: 4 3 2
